# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# echo "deb [signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
     

name: Python application with MongoDB

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:
    

permissions:
  contents: read

jobs:
  build-lint-test-mongodb:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run REST API Server
      run: |
        python --version
        uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4 &
        sleep 5
        sudo netstat -tulnp | grep 8000
        curl http://localhost:8000/get_hostname
        curl http://localhost:8000/get_ror
        curl http://localhost:8000/list_sut
    - name: Test REST API GET
      run: |
        python --version
        python ./tests/test_fastapi.py
    - name: Test REST API SET-GET
      run: |
        python --version
        python ./tests/test_fastapi_setror.py

    - name: Install MongoDB to Ubuntu Linux
      continue-on-error: true
      run: |
        lsb_release -cs
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
        echo "deb [signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt -y update
        sudo apt install -y mongodb-org
        sudo systemctl start mongod
        sudo systemctl enable mongod
        sudo systemctl status mongod
        mongod --version
    - name: Test REST API with MongoDB
      run: |
        python --version
        python ./tests-mongodb/test_fastapi_setror_mongodb.py
        python ./tests-mongodb/test_fastapi_query_mongodb.py mongo_ror_collection

        
